### FindSomAs: Find homologs of the somA locus in Coprinopsis cinerea and friends
# ===========================================================================

## ---- General parameters ----
# Variables
FLANKs: 7000

# Scripts
hmmer2bed: "workflow/scripts/hmmer2bed.py"

# HMMER output
path2hmmers: "data/HMMERresults"

# -----------------------------
# Below there are two blocks, choose one at a time to run the pipeline:
# Augustus or not?
# -----------------------------

## ---- Genbank annotation files ---- 
# Are the annotations produced with Augustus? True or False
Augustus: False

GenomesIDs: ["Psicy2", "LU_PSS_1.0", "Corgl3", "MGC_Penvy_1", "CC3", "Copmar1", "Copmic2", "Copph3", "Coprinellus_aureogranulatus_MPG-14n_reassembly", "Laccaria_amethystina_LaAM-08-1_v1.0", "ASM412641v1", "LU_COA_1.0", "Candolleomyces_eurysporus_reassembly_enz", "Candolleomyces_efflorescens_reassembly_enz", "V1.0", "Agabi_varbisH97_2"]

path2genomes: "path/to/assemblies/and/annotations/from/GenBank"

# ## ---- Augustus annotation files ----
# # Are the annotations produced with Augustus? True or False
# Augustus: True

# GenomesIDs: ["C_micaeus_DM1047", "C_micaeus_w1", "GCA_900156845.1_ASM90015684v1", "GCA_951394405.1_gfCopMica1.1"]


